server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /base.qcow2 {
        alias /assets/boite-base.qcow2;
        add_header Content-Type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="boite-base.qcow2"';
    }

    location / {
        try_files $uri $uri/ =404;
    }
}